### ISSUE TITLE
motivation, context?

### ISSUE THREAD

**Issue by dckc** [ufbmi/dtm-json-to-owl#1]
This looks like an interesting topic. What motivated development of this code? In what context do you plan to use it?

**Comment by dckc** [comment]
oh... by way of introduction: I'm at KUMC, leading [Infrastructure and Software Development in GPC](https://informatics.gpcnetwork.org/trac/Project/wiki/SoftwareDev), our PCORNet CDRN, among other things. In a  previous life, I worked on the OWL specs: https://www.w3.org/TR/2004/REC-owl-features-20040210/#s7

**Comment by hoganwr** [comment]
Dan,

I believe I hosted the panel you presented in last Monday.

This code is for a project on a funded grant.  We are part of the MIDAS
(Modeling Infectious Disease Agent Study) research network funded by NIGMS.

As part of that work, we hacked up a Digital Commons where I think the data
just exist in JSON.  We want to convert the Digital Commons to our
Ontology-based Catalog of Infectious Disease Epidemiology (OBC.ide) to make
the digital objects searchable.

So I was converting a subsest of the objects into our OWL-based
representation of things.

As code goes, it's really lousy code - not nearly modular enough,
long-winded, etc.

But it does what I needed it to do.  I loaded the OWL file it outputs into
a triple store with the rest of OBC.ide and started writing some SPARQL
queries against it.

Bill

**Comment by dckc** [comment]
Oh... right.. Hi, Bill! The dog avatar threw me off :)

Oh boy... a whole pile of new acronyms. For reference, this is what a few quick searches turned up:

 - [MIDAS Resources](http://www.epimodels.org/drupal/?q=node/5)
   - link to http://ide.obc.io/ isn't working for me.
 - [MIDAS ONTOLOGY BASED CATALOG](http://www.epimodels.org/drupal-new/?q=node/110)
 - [The Apollo Structured Vocabulary: an OWL2 ontology of phenomena in infectious disease epidemiology and population biology for use in epidemic simulation](https://jbiomedsem.biomedcentral.com/articles/10.1186/s13326-016-0092-y)

If this turns into more than a quick-and-dirty conversion tool, I suggest citing a few of those in your README. But your answer is good enough for what I need. Thanks!
